name: Lint CI
on:
  pull_request:
  push:
    branches: [ master ]
  release:
    types: [ published ]
  workflow_dispatch:

env:
  TERM: xterm

jobs:
  shell-lint:
    name: Lint the shell code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Lint with shellcheck and shfmt
        uses: luizm/action-sh-checker@v0.9.0
        env:
          SHELLCHECK_OPTS: >-
            --enable add-default-case
            --enable avoid-nullary-conditions
            --enable check-unassigned-uppercase
            --enable deprecate-which
            --enable quote-safe-variables
            --enable require-variable-braces
          SHFMT_OPTS: >-
              --case-indent
              --func-next-line
              --indent 2
              --space-redirects
